max-players = "%max_players%"

online-mode = false

server-ip = "%ip%"
server-port = "%port%"

allow-flight = false
allow-nether = true
allow-end = true

view-distance = 12
simulation-distance = 6
entity-broadcast-range-percentage = 500

spawn-protection = 0
pvp = true